#Github Actions workflow for Ansible playbook execution
name: Ansible CI/CD Example Forked

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    lint: 
        name: Lint Ansible Playbook
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.9'
    
            - name: Install Ansible and dependencies
              run: |
                python -m pip install --upgrade pip
                pip install ansible ansible-lint
                pip install --upgrade ansible-lint
    
            - name: Run Ansible Lint
              run: ansible-lint playbooks/

    run_playbook:
        name: Run Ansible Playbook
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.9'
    
            - name: Install Ansible and dependencies
              run: |
                 python -m pip install --upgrade pip
                 pip install ansible
    
            - name: Run Ansible Playbook
              run: ansible-playbook playbooks/site.yml -i localhost
